FROM node:6.3.1

RUN apt-get update && apt-get install -y \
    inotify-tools \
    ruby \
    && rm -rf /var/lib/apt/lists/* \
    && gem install sass

RUN mkdir /frontend
WORKDIR /frontend

COPY package.json /frontend
RUN npm install

ADD . /frontend

CMD ["/frontend/node_modules/.bin/brunch", "watch", "-d"]
