version: '2'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
      - '1025:1025'
    volumes:
      - .:/go/src/github.com/lukad/helix
      - public:/frontend/public

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - public:/frontend/public

volumes:
  public:
    driver: local
