FROM golang:1.6.3-alpine

RUN apk add --update git mercurial

RUN go get github.com/skelterjohn/rerun

ADD . /go/src/github.com/lukad/helix

WORKDIR /go/src/github.com/lukad/helix

RUN go get

RUN go build

CMD rerun github.com/lukad/helix
